version: "3"
services:
  url_shortener:
    image: postgres:16.2
    container_name: url_shortener
    platform: linux/amd64 #for platform error on Apple M1 chips
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password_123
      POSTGRES_DB: url_shortener_db
    ports:
      - "5432:5432"
